=== Cr1Tyzen/University-Projects/Proiect Tehnologii Web/Tema3XML/comanda_magazin_online.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="Comanda">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Nr_Comanda" type="xs:string"/>
                <xs:element name="Data_comanda" type="xs:date"/>  <!-- foloseste formatul An-luna-zi udpa standardul xsd -->
                <xs:element name="Client">
                    <xs:complexType> 
                        <xs:sequence>   
                            <xs:element name="Client_ID" type="xs:string"/>
                            <xs:element name="Nume" type="xs:string"/>
                            <xs:element name="E-mail" type="xs:string"/>
                            <xs:element name="Adresa">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="Strada" type="xs:string"/>
                                        <xs:element name="Oras" type="xs:string"/>
                                        <xs:element name="Cod_Postal" type="xs:string"/>
                                        <xs:element name="Tara" type="xs:string"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Produse">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Produs" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="ID_Produs" type="xs:string"/>
                                        <xs:element name="Nume_produs" type="xs:string"/>
                                        <xs:element name="Cantitate" type="xs:int"/>
                                        <xs:element name="Pret" type="xs:decimal"/>
                                        <xs:element name="Pret_total" type="xs:decimal"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Comanda_Pret_Total" type="xs:decimal"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== Cr1Tyzen/University-Projects/Proiect Tehnologii Web/Tema3XML/comanda_magazin_online.xml
<?xml version="1.0" encoding="UTF-8"?>
<Comanda xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="comanda_magazin_online.xsd">
    <Nr_Comanda>12345</Nr_Comanda>
    <Data_comanda>2024-04-22</Data_comanda>
    <Client>
        <Client_ID>98765</Client_ID>
        <Nume>Ion Popescu</Nume>
        <E-mail>ion.popescu2523@yahoo.com</E-mail>
        <Adresa>
            <Strada>Strada Carol 1, Nr. 115</Strada>
            <Oras>Bucuresti</Oras>
            <Cod_Postal>010101</Cod_Postal>
            <Tara>Romania</Tara>
        </Adresa>
    </Client>
    <Produse>
        <Produs>
            <ID_Produs>111</ID_Produs>
            <Nume_produs>Telefon Mobil</Nume_produs>
            <Cantitate>1</Cantitate>
            <Pret>2000.00</Pret>
            <Pret_total>2000.00</Pret_total>
        </Produs>
        <Produs>
            <ID_Produs>222</ID_Produs>
            <Nume_produs>Husa Telefon</Nume_produs>
            <Cantitate>1</Cantitate>
            <Pret>50.00</Pret>
            <Pret_total>50.00</Pret_total>
        </Produs>
    </Produse>
    <Comanda_Pret_Total>2050.00</Comanda_Pret_Total>
</Comanda>
